services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    env_file: .env.local
    ports:
      - 3000:3000
    restart: always
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/var/www/teamproject/.well-known:/var/www/teamproject/.well-known"
      - "/etc/letsencrypt/live/teamproject.site/fullchain.pem:/etc/letsencrypt/live/teamproject.site/fullchain.pem"
      - "/etc/letsencrypt/live/teamproject.site/privkey.pem:/etc/letsencrypt/live/teamproject.site/privkey.pem"
    ports:
      - 80:80
      - 443:443
