import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../../scss/global.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const roboto = Roboto({ 
  subsets: ["cyrillic"],
  weight: ['400', '500', '700', '900'],
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={roboto.className}>
        <Header />
          <main className="wrapper">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
